{{- if .Values.config }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cerebro.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cerebro.labels" . | nindent 4 }}
data:
{{- range $path, $config := .Values.config }}
  {{ $path }}: |
{{ tpl $config $ | indent 4 -}}
{{- end -}}
{{- end -}}